#!/bin/sh /etc/rc.common
#
# Copyright (C) 2018 Lienol
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=91

CONFIG=ssr_server
CONFIG_FILE=/var/etc/$CONFIG.json
PID_FILE=/var/run/$CONFIG.pid
LOG_FILE=/var/log/$CONFIG.log
USERS=''

uci_get_by_type() {
	local index=0
	if [ -n $4 ]; then
		index=$4
	fi
	local ret=$(uci get $CONFIG.@$1[$index].$2 2>/dev/null)
	echo ${ret:=$3}
}

is_true() {
	case $1 in
		1|on|true|yes|enabled) echo 0;;
		*) echo 1;;
	esac
}

load_config() {
	ENABLED=$(uci_get_by_type server enable)
	return $(is_true $ENABLED)
}

start_server() {
	mkdir -p  /var/etc
	/usr/bin/python \
	/usr/share/ssr/shadowsocks/server.py  \
	-c $CONFIG_FILE  \
	--pid-file $PID_FILE  \
  --log-file $LOG_FILE  \
  -d start  \
	>/dev/null 2>&1 &
}

gen_config_file() {
	config_load ssr_server
	config_foreach setup_users users
	FINAL=`echo ${USERS: -1}`
	if [ "$FINAL" == "," ]; then
	USERS=${USERS:0:${#USERS}-1}
	fi
	cat <<-EOF >$CONFIG_FILE
		{
		    "server": "::",
		    "local_address":"127.0.0.1",
		    "local_port":1086,
		    "timeout": $(uci_get_by_type server timeout 60),
		    "method": "$(uci_get_by_type server encrypt_method)",
		    "protocol": "$(uci_get_by_type server protocol)",
		    "protocol_param": "$(uci_get_by_type server protocol_param)",
		    "obfs": "$(uci_get_by_type server obfs)",
		    "obfs_param": "$(uci_get_by_type server obfs_param)",
		    "redirect": "$(uci_get_by_type server redirect)",
		    "fast_open": "$(uci_get_by_type server fast_open)",
		    "port_password": {$USERS}
		}
EOF
}

setup_users() {
	local section="$1"
	config_get enabled "$section" enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get port "$section" port
	config_get password "$section" password
	[ -n "$port" ] || return 0
	[ -n "$password" ] || return 0
	USERS=$USERS"\"$port\"":"\"$password\"",
}

start() {
	! load_config && exit 0
	gen_config_file "server"
	start_server
}

stop() {
	/usr/bin/python \
	/usr/share/ssr/shadowsocks/server.py  \
	-c $CONFIG_FILE  \
	--pid-file $PID_FILE  \
  --log-file $LOG_FILE  \
	-d stop  \
	>/dev/null 2>&1 &
	rm -f $LOG_FILE
}